# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

social:
  github: https://github.com/kakiezhang
  weibo: http://weibo.com/kakiezhang

# Miscellaneous
google_analytics:
favicon: http://laokela.net/s-static/css/captain_mod.jpg
twitter:
google_plus:
fb_admins:
fb_app_id:
